### ISSUE TITLE
Warning:  Promise.defer is deprecated... Use new Promise instead.

### ISSUE THREAD

**Issue by awatson1978** [Submersible/node-python-bridge#1]
Hi there, 
So, grad school started, I have profs wanting assignments turned in using Python; but I'm accustomed to programming in Meteor/Node.  So, I'm trying to integrate `node-python-bridge` into a Meteor app.   Run algorithms with Python, display on a reactive Meteor app.  Sounds like that could be a useful tool, right?  Well it does to me, anyhow.

**Environment**  
So, the environment I'm using is as follows:
- Meteor:  v1.4.1.1  
- Node:     v2.15.9  
- Node-Gyp:  v3.4.0  
- Mac:  10.11.5 (El Capitan)

**Initial Error**  
Got the initial Meteor app set up; installed `node-python-bridge`, but am getting the following error from [Line 137](https://github.com/Submersible/node-python-bridge/blob/master/index.js#L137) when I run the app:

``` sh
W20160920-19:08:18.851(-5)? (STDERR) Warning: Promise.defer is deprecated and will be removed in a future version. Use new Promise instead.
W20160920-19:08:18.944(-5)? (STDERR)     at enqueue (/Users/abigail/Code/meteor-python/node_modules/python-bridge/index.js:137:29)
W20160920-19:08:18.945(-5)? (STDERR)     at Function.wrapper [as ex] (/Users/abigail/Code/meteor-python/node_modules/python-bridge/index.js:35:20)
W20160920-19:08:18.945(-5)? (STDERR)     at meteorInstall.server.main.js (server/main.js:10:8)
W20160920-19:08:18.946(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160920-19:08:18.946(-5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160920-19:08:18.946(-5)? (STDERR)     at /Users/abigail/Code/meteor-python/.meteor/local/build/programs/server/app/app.js:38:1
W20160920-19:08:18.947(-5)? (STDERR)     at /Users/abigail/Code/meteor-python/.meteor/local/build/programs/server/boot.js:292:10
W20160920-19:08:18.947(-5)? (STDERR)     at Array.forEach (native)
W20160920-19:08:18.948(-5)? (STDERR)     at Function._.each._.forEach (/Users/abigail/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160920-19:08:18.948(-5)? (STDERR)     at /Users/abigail/Code/meteor-python/.meteor/local/build/programs/server/boot.js:128:5
```

**Attempted Fix**  
I've not entirely learned the new `Promise` syntax; so I thought this would be a good time to try to familiarize myself with it.  This is the fix that I came up with:

``` js
// Only a single Python worker process can be asynchronously running at a time,
// which means that only a single python _function_ can be running at a time.
// If a new worker function is queued up; it forces the bridge to try to resolve
// the last worker process.

function singleQueue() {
  return function enqueue(f) {
    return new Promise(function(resolve, reject){
      Promise.try(f).then(resolve, reject);
    });
  };
}


// function singleQueue() {
//     let last = Promise.resolve();
//     return function enqueue(f) {
//         let defer = Promise.defer();
//         let wait = last;
//         last = defer.promise;
//         return new Promise((resolve, reject) => {
//             wait.finally(() => {
//                 Promise.try(f).then(resolve, reject);
//             });
//         }).finally(() => {
//             defer.resolve();
//         });
//     };
// }
```

**Subsequent Error**  
This produces an `IOError: [Errno 32] Broken pipe` error, which I _think_ is a good sign.  Or I might be walking off a cliff here.  I'm not sure which. 

``` sh
[[[[[ ~/Code/Biomedical/meteor-python ]]]]]   

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
W20160920-19:31:23.361(-5)? (STDERR) Traceback (most recent call last):
W20160920-19:31:23.428(-5)? (STDERR)   File "/Users/abigail/Code/meteor-python/node_modules/python-bridge/node_python_bridge.py", line 61, in <module>
W20160920-19:31:23.428(-5)? (STDERR)     writer.flush()
W20160920-19:31:23.429(-5)? (STDERR) IOError: [Errno 32] Broken pipe
W20160920-19:31:23.429(-5)? (STDERR) close failed in file object destructor:
W20160920-19:31:23.429(-5)? (STDERR) IOError: [Errno 9] Bad file descriptor
```

Any ideas if I'm on the right path here? Does that `singleQueue()` function look correct as it's rewritten?    

Thanks in advance for taking a look at this problem!

**Comment by awatson1978** [comment]
Also, by the way....  awesome project.  It totally works despite the deprecation warning.   

Oh, and here's a reproduction of the error:
https://github.com/awatson1978/meteor-python

**Comment by munro** [comment]
Ah woops, accidentally responded to the email.  Usually my github email gets random emails from people... nobody actually creates issues!  😄 

> Hey pushed a fix out!  You may be totally correct that locking isn’t necessary—I vaguely remember writing this stuff, most likely did it just to be on the safe side.

> I tried a few ways of simplifying it too, but the tests wouldn’t pass.  So at the very least, it’s nice to see my past self wrote better tests [1] than code. 👏

> If you experience any bugs, let me know and I can try to write a test to reproduce it.  If you want to try and shorten the code I would totally merge it!

> [1] https://github.com/Submersible/node-python-bridge/blob/master/test.js

**Comment by munro** [comment]
Oh, actually, did removing usage of `Promise.defer` [1] fix the warning for you?

[1] https://github.com/Submersible/node-python-bridge/commit/8e05002ae374f183b3e2634339def6402b60cca3

**Comment by munro** [comment]
https://github.com/Submersible/node-python-bridge/commit/8e05002ae374f183b3e2634339def6402b60cca3 fixed the warning, closing issue!
