### ISSUE TITLE
Fail under strict checking: implicitly has an 'any' type

### ISSUE THREAD

**Issue by zixia** [Submersible/node-python-bridge#12]
I have using the latest npm module with TypeScript support in my project.

I'm using strict type checking, so this line failed:

```
tslint --project tsconfig.json --type-check && npm run clean && tsc --noEmit

Error at node_modules/python-bridge/index.d.ts:55:13: Parameter 'number' implicitly has an 'any' type.
```
<https://github.com/Submersible/node-python-bridge/blob/master/index.d.ts#L55>

I suggest we add a strict checking inside our project.

**Comment by munro** [comment]
Awesome, thanks a lot!  Sorry for the delay, your changes are published now yay `yarn add python-bridge@1.0.2`
