### ISSUE TITLE
stdout/stderr are null?

### ISSUE THREAD

**Issue by rein-dc** [Submersible/node-python-bridge#19]
Hello,

When I do the following:

```
let pythonBridge = require('python-bridge');
let python = pythonBridge();
```

python.stdin contains an object but stdout and stderr are null - maybe due to something else unrelated

However I think this is mainly because of the default options for stdio. So I tried passing in 'pipe' into 2nd arg to options.stdio on startup such as below:

```
let python = pythonBridge({  stdio: ['pipe','pipe', process.stderr] });
python.stdout.pipe(someStream);
```

Now stdout does seem to work better so I am guessing 'pipe' is a magic word somewhere that makes things work. I am on OSX running Python 3.

**Comment by munro** [comment]
oh, that's correct behavior.  it works identical to the way node's `child_process.spawn` work[1]—I actually just copy the `subprocess.std*` properties to the `python.*` object. [2]

the default is `['pipe', process.stdout, process.stderr]`, so you can feed in your own `stdin` (or just not even touch it), and stdout & stderr are forwarded directly to the terminal.

[1] https://nodejs.org/api/child_process.html#child_process_subprocess_stderr
[2] https://github.com/Submersible/node-python-bridge/blob/master/index.js#L98-L100
