### ISSUE TITLE
How to execute py file through node-python-bridge?

### ISSUE THREAD

**Issue by jaideepsengar** [Submersible/node-python-bridge#20]
Hi,

I have a requirement to execute a py file through my node service, i earlier used https://github.com/extrabacon/python-shell to execute py files but it doesn't have good error handling and option to open bridges.
I was going through node-python-bridge and it looks good to me to execute python code but i am not able to execute py files through it.

Is there any way to execute py files?
can we make line https://github.com/Submersible/node-python-bridge/blob/731055d9e3e240776509fc4e911f4f3cd348cf3b/index.js#L22 more dynamic to accept user input python file?

**Comment by munro** [comment]
`PYTHON_BRIDGE_SCRIPT` sets up all the hooks to forward python errors & stdio.

```python
python.ex`exec(open("my_python_script.py").read())`
```
^ this should work for you, and will forward python errors & stdio 💥

**Comment by jaideepsengar** [comment]
Just wanted to add for python 2.7 we need `python.ex`execfile("my_python_script.py"))`` But i am not getting any output if we don't have return statement in my python script, how to get print method output?

**Comment by gautamchitnis** [comment]
> `PYTHON_BRIDGE_SCRIPT` sets up all the hooks to forward python errors & stdio.
> 
> ```js
> python.ex`exec(open("my_python_script.py").read())`
> ```
> 
> ^ this should work for you, and will forward python errors & stdio 💥

Tried it, but getting the following error:
```TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Promise```

**Comment by gautamchitnis** [comment]
> > `PYTHON_BRIDGE_SCRIPT` sets up all the hooks to forward python errors & stdio.
> > ```js
> > python.ex`exec(open("my_python_script.py").read())`
> > ```
> > 
> > 
> > ^ this should work for you, and will forward python errors & stdio 💥
> 
> Tried it, but getting the following error:
> `TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Promise`

So i was able to figure out why that error was showing up. It seems ```pyhton.ex``` returns a ```Promise``` object. It would be great if some one can provide info on how to get the actual data in a variable.

**Comment by munro** [comment]
> So i was able to figure out why that error was showing up. It seems pyhton.ex returns a Promise object. It would be great if some one can provide info on how to get the actual data in a variable.

oh yea, everything is async.  if you `await python.ex`, that will guarantee the script finished executing.  so if the script writes to `stdout`, you'll have to setup some code to capture from `python.stdout` **before** executing your script, so you can catch all of the output.

alternatively, I would recommend modifying `my_python_script.py` to instead contain a function that returns the output you want to bring over to node.js, and then call that function to capture the output, so something like this:

**my_python_script.py**
```python
def get_some_data_in_python():
    return 124
```

**my_node_script.js**
```javascript
await python.ex`exec(open("my_python_script.py").read())`
const my_data = await python`get_some_data_in_python()`
```

one last thing, instead of doing `` await python.ex`exec(open("my_python_script.py").read())` ``, you could make sure your `PYTHONPATH` is correct, and do `` await python.ex`from my_python_script import get_some_data_in_python` ``, which may look prettier. 😄 

I hope that helps!

**Comment by gautamchitnis** [comment]
> > So i was able to figure out why that error was showing up. It seems pyhton.ex returns a Promise object. It would be great if some one can provide info on how to get the actual data in a variable.
> 
> oh yea, everything is async. if you `await python.ex`, that will guarantee the script finished executing. so if the script writes to `stdout`, you'll have to setup some code to capture from `python.stdout` **before** executing your script, so you can catch all of the output.
> 
> alternatively, I would recommend modifying `my_python_script.py` to instead contain a function that returns the output you want to bring over to node.js, and then call that function to capture the output, so something like this:
> 
> **my_python_script.py**
> 
> ```python
> def get_some_data_in_python():
>     return 124
> ```
> 
> **my_node_script.js**
> 
> ```js
> await python.ex`exec(open("my_python_script.py").read())`
> const my_data = await python`get_some_data_in_python()`
> ```
> 
> one last thing, instead of doing `` await python.ex`exec(open("my_python_script.py").read())` ``, you could make sure your `PYTHONPATH` is correct, and do `` await python.ex`from my_python_script import get_some_data_in_python` ``, which may look prettier. 😄
> 
> I hope that helps!

Thank you for the help! I'd come to a similar conclusion, but didn't understand how calling the function would work, which your code clearly demonstrates so thanks again! As a side note, I was not able to figure out how to do the set up for ```python.stdout``` capture based on available documentation, so maybe you could provide a snippet if possible @munro :) as that would help anyone else coming here for that. Also, if you want to create some samples showing basic and advanced usage of the library, I'd be happy to collaborate as this seems like a very useful library and some detailed documentation could go a long way in helping new users.

**Comment by munro** [comment]
> As a side note, I was not able to figure out how to do the set up for `python.stdout` capture based on available documentation

I haven't been using Node.js as much these days, so not sure what the slickest way to do this is, but essentially you would have to create a buffer, then read in the stream and append to that in memory buffer.  One complication with this approach is it could be hard to know when to cut off reading from the stream.  I do see a `get-buffer` package on NPM, so I'm thinking this could be pretty slick:

```javascript
// I haven't tested this code!
const dataPromise = require('get-buffer').fromStream(python.stdout);
await python.ex`exec(open("my_python_script.py").read())`;
await python.quit();
const data = await dataPromise;
```

> Also, if you want to create some samples showing basic and advanced usage of the library, I'd be happy to collaborate as this seems like a very useful library and some detailed documentation could go a long way in helping new users.

If you submit a PR adding a `Examples` section above `Comparisons`, I would be more than happy to merge it!

**Comment by gautamchitnis** [comment]
@munro I will try this out and definitely send a PR if it all works out! :) thanks for the support!
