### ISSUE TITLE
python-shell has a broken evaluation parser?

### ISSUE THREAD

**Issue by Almenon** [Submersible/node-python-bridge#21]
In your readme you say that:

> python-shell — No promises for queued requests; broken evaluation parser; conflates evaluation and stdout; complex configuration.

what do you mean by broken evaluation parser?

**Comment by munro** [comment]
hmmm maybe it's fixed now but I remember having issues where if a string included `>>>` it would parse it as a new command.

**Comment by munro** [comment]
is that still the case?

**Comment by Almenon** [comment]
Ooops, somehow your response totally slipped my radar, sorry.

It's not still the case. Python-shell doesn't do anything special upon encountering the string ">>>" - if you clone the repo and search for it you can see there are no results. The only parsing python-shell does is parsing of stdout&stderr.
