### ISSUE TITLE
python.ex`${src}` is broken

### ISSUE THREAD

**Issue by CreatorVilius** [Submersible/node-python-bridge#23]
I can't do python.ex`${src}` for some reason. Though, it's problem with node js.

Is there any chance we are getting `python.ex2('something here')` also?

**Comment by munro** [comment]
Ahhh good point does, this should work in the meantime, can you try it?

```javascript
python.ex`${src}`
```

**Comment by CreatorVilius** [comment]
I tried, it literally outputs as blank. Even though `src` is defined. It's problem with node js, but still, we need python.ex2() maybe?

**Comment by munro** [comment]
Ohhh `python.ex` is for executing statements, Python will never return anything.  Try doing `python``${src}``` to evaluate and expression and get the value back.

**Comment by munro** [comment]
@CreatorVilius If you send me a PR with a broken test case, I'll get it fixed for you!  :)

**Comment by rothn** [comment]
Got a test case for you:

This works:
pythonWorker.ex`print("Hello world!")`;

This does nothing:
let string = 'print("Hello world!")';
pythonWorker.ex`${string}`;

**Comment by rothn** [comment]
Might I add that obscure and opaque syntax can sometimes cause more problems than it solves (e.g. making it hard for individual developers to find out what's going wrong)

**Comment by rothn** [comment]
For others having this issue, here's the fix:
Edit index.js in the package

1) Navigate to sendPythonCommand
2) Change the line `let code = json.apply(this, arguments);` to `let code = arguments[0]`
3) Call like pythonWorker.ex('code_to_run')

Note that this will execute the code verbatim, so you need to be aware of spacing and other Pythonic things. I like to `pythonWorker.ex(fs.readFileSync('my_init_file.py'))`

**Comment by munro** [comment]
@rothn awesome!  could you submit a PR?  no need to have everyone hacking together a solution if you have one already. :)

**Comment by rothn** [comment]
I can make a PR if you're OK with the following limitations:
* This breaks automatic reformatting of multi-line inline statements
* This changes the syntax from python.ex`print("foo")` to python.ex('print("foo")')

**Comment by munro** [comment]
```javascript
python.ex`exec(${src})`
```
☝️The solution is to do this—and I can't foresee this changing for any reason, correct interpolation is important, and I don't want to directly concatenate bits of Python code.  I could foresee adding a new method to execute Python code, but 1) exec works perfectly 2) other option is to create the Python code as module & import it, which will give better stack traces as well.  I think what would change my mind is either a) a pull request b) if it's the case that `exec` doesn't give good stack traces.
