### ISSUE TITLE
run a python file ?

### ISSUE THREAD

**Issue by lloxis** [Submersible/node-python-bridge#34]
How can I run a python file with node-python-bridge instead of directly writing all of my code in a javascript string ?

**Comment by huan** [comment]
You can import your python module first:

https://github.com/huan/node-facenet/blob/57c16258779b1a3ac03c121e9522323b3913a562/src/python3/python-facenet.ts#L105

Then you will be able to call a function in Python and return the result to JavaScript:

https://github.com/huan/node-facenet/blob/57c16258779b1a3ac03c121e9522323b3913a562/src/python3/python-facenet.ts#L147

**Comment by munro** [comment]
@lloxis yes thank you @huan 

I would strongly recommend using an import; or using `fs` to read the file and then do `python.ex(code)`; or you could do ``python.ex`exec(open("./filename.py").read())` `` (even Python 3 removed `execfile`)!  There are so many ways to execute a Python file 🤣—and I want to keep the surface area of this library as small as possible.

And depending on the context, you may not even need this library if you're simply executing a file—you can also do `child_process.spawn("python", ["my_script.py"])`.

I hope that helps!
