### ISSUE TITLE
EOL error when "\n" in python script

### ISSUE THREAD

**Issue by fangrouli** [Submersible/node-python-bridge#37]
Hi! First of all it is a wonderful package that allows me to call python script from Node.js super fast and easy. There is one problem that I encountered during the work though. 

In side my python script I need to return a string that requires a "\n" in side. For example:
` return "Path: " + path + "\nVersion: " + version `

But when there is this new line, the EOL error will appear:

> return "Path: " + path + "
    	                                   ^
SyntaxError: EOL while scanning string literal

(the ^ is right below the ")

So basically the system cannot read the "\n" and take it as the end of the string.

After I removed the "\n", no more EOL error and the script runs smoothly. But the output becomes messy as it is hard to read without the line break.

May I know whether this issue does exist, and whether there is any solution or work-arounds?

thank you for the excellent work btw!

A more detailed error msg in case needed:

> stack trace: Error: Traceback (most recent call last):
  File "c:\Users\***\node_modules\python-bridge\node_python_bridge.py", line 101, in <module>
    _exec(_compile(data['code'], '<input>', 'exec'), _locals)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\codeop.py", line 143, in __call__
    codeob = compile(source, filename, symbol, self.flags, True)
  File "<input>", line 8
    	return "Path: " + path + "
    	                          ^
SyntaxError: EOL while scanning string literal
	at ChildProcess.onMessage (c:\Users\***\node_modules\python-bridge\index.js:44:32)
	at Object.onceWrapper (events.js:422:26)
	at ChildProcess.emit (events.js:315:20)
	at emit (internal/child_process.js:903:12)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by munro** [comment]
@fangrouli Tyty 💗 Could you share what a snippet of what the JS & Python looks like that reproduces it?

**Comment by fangrouli** [comment]
py.ex`
        def dummy():
            print('Hello\nworld)`;
py`dummy()`

you can try this (in JavaScript) and run it in Node.js

**Comment by fangrouli** [comment]
`py.ex"  
        def dummy():  
            print('Hello\nworld)";  
py"dummy()";  
`

sorry about the format, please replace the " with `

**Comment by munro** [comment]
Ah yea so inside the JavaScript string `` `...` `` goes the Python code, but we're still in JavaScript, so `\n` gets converted into a new line.

Try doing switching `py.ex` with `console.log` to see what the Python code that's going to execute is going to look like.

You can use string interpolation so that `"Hello\nworld"` is encoded properly before getting passed to the Python process like this:

```typescript
await py.ex`
    def dummy():  
        print(${"Hello\nworld"})
`;
await py`dummy()`;
```
