### ISSUE TITLE
TypeScript Defination Support?

### ISSUE THREAD

**Issue by zixia** [Submersible/node-python-bridge#9]
Hi, @mickdekkers !

Thanks for your great project, I'm planning to use node-python-bridge to call TensorFlow in Node.js.

Because I'm a big TypeScript fan, so I'd like to suggest adding a typing definition file in this project, which could benefit us from the static type checking and vscode IntelliSense from TypeScript.

Or be better, rewrite the `index.js` in TypeScript.

If you agree with that, I'd be very like to contribute.

**Comment by munro** [comment]
Hey @zixia I don't know too much about TypeScript, but this is what I whipped up

```typescript
import {Writable, Readable} from "stream";

declare module "python-bridge" {
  export default function python({intepreter, stdio, cwd, env, uid, gid}: PythonBridgeOptions): PythonBridge;

  export interface PythonBridgeOptions {
    intepreter: string;
    stdio?: [PipeStdin, PipeStdout, PipeStderr];
    cwd?: string;
    env?: { [key:string]: string; };
    uid?: number;
    gid?: number;
  }

  export interface PythonBridge {
    (literals: TemplateStringsArray | string, ...placeholders: any[]): Promise<any>;
    ex(literals: TemplateStringsArray | string, ...placeholders: any[]): Promise<void>;
    lock<T>(withLock: (python: PythonBridge) => Promise<T>): Promise<T>
    pid: number;
    end(): Promise<void>;  
    disconnect(): Promise<void>;
    kill(signal: string | number): void;
    stdin: Writable;
    stdout: Readable;
    stderr: Readable;
    connected: boolean;
  }

  export class PythonException extends Error {
    error: any;  // @TODO what is this type
    exception: any;  // @TODO what is this type
    traceback: any;  // @TODO what is this type
    format: any;  // @TODO what is this type
  }

  export function isPythonException(e: any): boolean;

  export type Pipe = "pipe" | "ignore" | "inherit";
  export type PipeStdin = Pipe | Readable;
  export type PipeStdout = Pipe | Writable;
  export type PipeStderr = Pipe | Writable;
}
```

Unfortunately I'm still figuring out how to fully test this, do I just save it as `index.d.ts`, or do I need to define something else in the `package.json`?   Also how do you test if this works locally?

I've been doing a lot of python 3.6 lately, type completion is sooooo nice.  😄

**Comment by zixia** [comment]
Hi, @munro !

I just start learning the Python last month, and I also love the typing of Python 3.6 very much. I use `mypy` in my project with VSCode and Python plugin.

The Type Definition you just whipped up is awesome, I can't wait for use it. 

In order to use it, we need to:
1. put them in `index.d.ts` and put it somewhere;
1. add a `types` entry in `package.json`, pointing to the `index.d.ts`
1. add a unit test written in TypeScript, `import { PythonBridge } from './'`, add some function call with types. (Or better, fully rewrite the unit test to TypeScript)
1. use `tsc` to compile the unit test file, and run it.

I will do a Pull Request to demo them for you. :)

**Comment by zixia** [comment]
Cheers!
